CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role text NOT NULL UNIQUE CHECK (role IN ('admin', 'driver'))
);

INSERT INTO public.users (role)
SELECT role
FROM (VALUES ('admin'), ('driver')) AS seeded(role)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.users u
  WHERE u.role = seeded.role
);

CREATE TABLE IF NOT EXISTS public.sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  session_key text NOT NULL UNIQUE,
  session_token_hash text NOT NULL UNIQUE,
  jwt_jti text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  last_seen_at timestamp with time zone,
  revoked_at timestamp with time zone,
  revoked_reason text,
  user_agent text,
  ip_address inet,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON public.sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON public.sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_sessions_active_lookup
  ON public.sessions(user_id, revoked_at, expires_at);
